spring:
  cloud:
    gateway:
        routes:
          - id: r1
            uri: lb://CUSTOMER
            predicates:
              - Path= /customers/**
          - id: r2
            uri: http://localhost:8081
            predicates:
              - Path= /products/**