INSERT INTO DOCTOR_SPECIALITY (id, name, description) VALUES
    (404, 'NOT_ASSIGNED', 'Temporary'),
    (1, 'GENERAL_PRACTITIONER', 'Provides initial diagnosis and treatment for common illnesses and refers patients to specialists when needed.'),
    (2, 'HOSPITALIST', 'Specializes in caring for hospitalized patients and coordinates treatment plans with various departments.'),
    (3, 'EMERGENCY_MEDICINE', 'Handles acute and life-threatening conditions in the Emergency Department and stabilizes patients before transferring them to specialized care.'),
    (4, 'SURGEON', 'Performs surgical procedures with subspecialties like cardiovascular, orthopedic, and neurological surgery.'),
    (5, 'CONSULTANT', 'Senior doctor specialized in a specific field who provides expert opinions and oversees patient care in their specialty.'),
    (6, 'CARDIOLOGIST', 'Focuses on heart and cardiovascular system diseases, handling conditions like heart attacks and arrhythmias.'),
    (7, 'NEUROLOGIST', 'Treats disorders of the nervous system, including the brain and spinal cord, like epilepsy and strokes.'),
    (8, 'ONCOLOGIST', 'Specializes in diagnosing and treating cancer with subspecialties in medical, radiation, and surgical oncology.'),
    (9, 'ORTHOPEDIC_SURGEON', 'Treats musculoskeletal system issues such as joint replacements and fracture repairs.'),
    (10, 'PEDIATRICIAN', 'Focuses on the health of infants, children, and adolescents, managing both common and complex conditions.'),
    (11, 'GYNECOLOGIST_OBSTETRICIAN', 'Specializes in female reproductive health and childbirth, including prenatal care and delivery.'),
    (12, 'PSYCHIATRIST', 'Focuses on mental health disorders and provides therapy and medication for conditions like depression and anxiety.'),
    (13, 'PULMONOLOGIST', 'Treats lung and respiratory system diseases such as asthma and COPD.'),
    (14, 'GASTROENTEROLOGIST', 'Focuses on digestive system disorders, including liver diseases and gastrointestinal conditions.'),
    (15, 'NEPHROLOGIST', 'Specializes in kidney care and related diseases like kidney failure and hypertension.'),
    (16, 'ENDOCRINOLOGIST', 'Treats hormonal imbalances and endocrine system disorders like diabetes and thyroid issues.'),
    (17, 'DERMATOLOGIST', 'Specializes in skin, hair, and nail disorders like eczema and acne.'),
    (18, 'RADIOLOGIST', 'Interprets imaging studies like X-rays and MRIs to assist in diagnosing conditions.'),
    (19, 'ANESTHESIOLOGIST', 'Manages anesthesia during surgeries and monitors patient vital signs during operations.'),
    (20, 'RHEUMATOLOGIST', 'Focuses on autoimmune and musculoskeletal diseases like arthritis and lupus.'),
    (21, 'PATHOLOGIST', 'Studies tissues, cells, and organs to diagnose diseases, playing a critical role in diagnosing cancer and infections.'),
    (22, 'OPHTHALMOLOGIST', 'Specializes in eye care and surgery, treating conditions like glaucoma and cataracts.'),
    (23, 'OTOLARYNGOLOGIST', 'Treats ear, nose, and throat disorders like sinus infections and hearing loss.'),
    (24, 'UROLOGIST', 'Focuses on urinary tract and male reproductive system disorders like kidney stones and prostate issues.'),
    (25, 'HEMATOLOGIST', 'Specializes in blood disorders such as anemia, leukemia, and clotting diseases.');
